### ISSUE TITLE
Make damn documentation

### ISSUE THREAD

**Issue by Porkechebure** [ermaccer/Manhunt.PluginMH#1]
Documentation is barebone.

How to load models? How to set more models of the player? How to use all the ini options?
Document the damn thing, one can't boot up the game 200 times to figure out every option

**Comment by ermaccer** [comment]
Everything has comments in the .ini and the file required for adding more skins has them too, what's the issue?

**Comment by ermaccer** [comment]
Closing as old skin loader is no longer here and Wiki has a section on how to work with new skin format.
