### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by justtoask** [ermaccer/Manhunt.PluginMH#3]
I installed this trough manhunt fixer, but gives me an error "unable to load MHP.asi. error: 126". I tried reinstalling the the plugin from here, reinstalling ultimate ASI loader (the default one), but it doesn't work

**Comment by ermaccer** [comment]
While this issue is not related to PluginMH directly, try reinstalling/downloading C++ redists:
https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

or
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
